# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Murky Swamp
tagline:          'coding life!'
description:      'aim at full-stack developer...'
url:              http://davidx.me

author:
  name:           'David Xie'
  linkedin:       https://twitter.com/davidx_me
  github:         https://github.com/david-xie
  aboutme:        http://about.me/davidx
  linkedin:       https://www.linkedin.com/profile/view?id=57886859

paginate:         5

github:           https://github.com/david-xie
