# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            泥泞的沼泽
tagline:          '一个程序员的博客'
description:      '擅长Python, 主玩Linux/Mac, 涉猎范围比较广....'
url:              http://davidx.me

author:
  name:           'David Xie'
  linkedin:       https://twitter.com/davidx_me
  github:         https://github.com/kingheaven
  aboutme:        http://about.me/davidx
  linkedin:       https://www.linkedin.com/profile/view?id=57886859

paginate:         5

github:           https://github.com/kingheaven
